### ISSUE TITLE
Document view feature

### ISSUE THREAD

**Issue by maoouu** [maoouu/AMA_Scholarly#1]
Figuring out how to support **.docx**, **.doc** and other formats to the document viewer.

**Comment by maoouu** [comment]
@voliveros19 since pictures pala yun, may idea ako. Pano kung gawing isang pdf file yung mga group ng pictures sa isang folder?

**Comment by maoouu** [comment]
@voliveros19 

**.docx** ---> **lagyan ng watermark** ---> **jpeg** ---> **.pdf** yung gawin mo men

**Comment by sshhquinn** [comment]
iz done
